#!/usr/bin/env bash
# Atalho CLI do Audiblez (criado por install-audiblez.sh)
source "$HOME/audiblez-env/bin/activate"

if [ "$1" == "gui" ]; then
    shift
    audiblez-ui "$@"
else
    audiblez "$@"
fi